apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Specify resources to include in the build
resources:
- manager.yaml

# Generator options
generatorOptions:
  disableNameSuffixHash: true

# # Generate a ConfigMap from the specified file
# configMapGenerator:
# - files:
#   - controller_manager_config.yaml
#   name: manager-config

# Specify image replacements
images:
- name: ofcir-operator-image
  newName: localhost/ofcir
  newTag: latest
