# permissions for end users to view ciresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ciresource-viewer-role
  namespace: system
rules:
- apiGroups:
  - ofcir.openshift
  resources:
  - ciresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ofcir.openshift
  resources:
  - ciresources/status
  verbs:
  - get
