# permissions for end users to edit ciresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ciresource-editor-role
  namespace: system
rules:
- apiGroups:
  - ofcir.openshift
  resources:
  - ciresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofcir.openshift
  resources:
  - ciresources/status
  verbs:
  - get
