---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-fallback
spec:
  provider: libvirt
  priority: -1
  size: 2
  timeout: '4h'
  state: available
  type: host

---

apiVersion: v1
kind: Secret
metadata:
  name: cipool-fallback-secret
type: Opaque
stringData:
  config: |
    {
      "pool": "default",
      "volume": 20,
      "backing_store": "/tests/fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2",
      "memory": 4,
      "cpus": 2,
      "bridge": "virbr0",
      "ignition": "/tests/coreos.ign"
    }

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-libvirt
spec:
  provider: libvirt
  priority: 0
  size: 2
  timeout: '4h'
  state: available
  type: host

---

apiVersion: v1
kind: Secret
metadata:
  name: cipool-libvirt-secret
type: Opaque
stringData:
  config: |
    {
      "pool": "default",
      "volume": 20,
      "backing_store": "/tests/fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2",
      "memory": 4,
      "cpus": 2,
      "bridge": "virbr0",
      "ignition": "/tests/coreos.ign"
    }

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-ironic
spec:
  provider: ironic
  priority: 0
  size: 0
  timeout: '4h'
  state: available
  type: host

---

apiVersion: v1
kind: Secret
metadata:
  name: cipool-ironic-secret
type: Opaque
stringData:
  config: |
    {
      "username": "ironic-user",
      "password": "XXXX",
      "endpoint": "https://172.22.0.3:6385",
      "image": "http://172.22.0.1/images/ofcir_image.qcow2"
    }
